version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cepdb
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock